### ISSUE TITLE
Support for parralel task execution

### ISSUE THREAD

**Issue by wesleyjconnor** [camunda/camunda-external-task-client-java#16]
Our use case requires parallel task execution to most efficiently process our tasks. The current implementation supports requesting multiple tasks but still processes them sequentially. 
Is this feature planned? Or did I miss an option?

**Comment by koevskinikola** [comment]
Hi @wesleyjconnor,

Currently, the external task client doesn't support parallel task execution and there aren't any plans to provide it in the near feature. You can attempt to optimize by running multiple clients and distribute tasks by `business key`. There has already been a similar issue opened for the [External Task JS Client](https://github.com/camunda/camunda-external-task-client-js/issues/15) which implements the same features as this one, maybe the discussion there will help you.

Otherwise, you can contribute to this repository by providing a pull request, or, in case you are a Camunda customer, feel free to raise a Support ticket.

Best,
Nikola

**Comment by ingorichtsmeier** [comment]
A workround could be to set maxTasks to 1, use long polling with asyncResponseTimeout 90000 (90 sec) and start multiple workers. 

Now you can control hardware consumption by the OS.

**Comment by wesleyjconnor** [comment]
> A workround could be to set maxTasks to 1, use long polling with asyncResponseTimeout 90000 (90 sec) and start multiple workers.
> 
> Now you can control hardware consumption by the OS.

Yes I was considering a pool at the worker level.
Thanks for the input, I will see what I can do

**Comment by tasso94** [comment]
Hi,

I hope nothing remained unclear for you? 
If you have any further questions please feel free to open this issue again.

Cheers,
Tassilo

**Comment by shibin-aot** [comment]
Try this solution, this may suite for your use case.
https://www.linkedin.com/pulse/parallel-execution-camunda-external-task-shibin-thomas/?trackingId=gYNQEiDYS3aDfoIjRrvJOQ%3D%3D
